"""Phase 3 — spec creation and engine-asset stamping (the code parts; the Griller prompt
itself is exercised in a live Builder session)."""

from pathlib import Path

from conftest import install, method_text
from grillwork import naming, spec


def test_new_spec_creates_filled_draft(tmp_path):
    install(tmp_path)
    result = spec.new_spec(tmp_path, "Let users export their data as CSV")

    assert result["seq"] == "001"
    assert result["slug"] == "let-users-export-their-data-as-csv"
    assert result["id"] == "001-let-users-export-their-data-as-csv"

    # One folder per spec: <spec_home>/<NNN>-<slug>/spec.md
    path = Path(result["path"])
    assert path.name == "spec.md"
    assert path.parent.name == "001-let-users-export-their-data-as-csv"

    content = path.read_text(encoding="utf-8")
    assert "# Spec: Let users export their data as CSV" in content
    assert "001-let-users-export-their-data-as-csv" in content
    assert "[GAP G-002: summary]" in content  # unfilled sections carry markers


def test_new_spec_increments(tmp_path):
    install(tmp_path)
    first = spec.new_spec(tmp_path, "alpha")
    second = spec.new_spec(tmp_path, "bravo")
    assert first["seq"] == "001"
    assert second["seq"] == "002"


def test_record_finding_appends_structured_lines(tmp_path):
    install(tmp_path)
    path = Path(spec.new_spec(tmp_path, "alpha")["path"])

    first = spec.record_finding(path, gap="max file size unspecified", why="edge case never grilled", phase="build")
    findings = Path(first["path"])
    assert findings.name == "findings.md"
    assert findings.parent == path.parent  # sibling of the spec
    assert first["count"] == 1

    second = spec.record_finding(path, gap="empty-input behavior", why="boundary not in criteria")
    assert second["count"] == 2  # appends, does not overwrite

    text = findings.read_text(encoding="utf-8")
    assert "**gap:** max file size unspecified" in text
    assert "**phase:** build" in text
    assert "empty-input behavior" in text


def test_spec_status_reads_and_sets(tmp_path):
    install(tmp_path)
    path = Path(spec.new_spec(tmp_path, "alpha")["path"])

    # A fresh spec reads `drafting`; the dev loop advances it, deterministically.
    assert spec.spec_status(path)["status"] == "drafting"
    result = spec.spec_status(path, "building", changed_at="2026-07-12T00:00:00+00:00")
    assert result == {
        "path": str(path),
        "status": "building",
        "previous": "drafting",
        "changed_at": "2026-07-12T00:00:00+00:00",
    }
    assert spec.spec_status(path)["status"] == "building"


def test_spec_status_stamps_the_transition_time(tmp_path):
    install(tmp_path)
    path = Path(spec.new_spec(tmp_path, "alpha")["path"])

    # new_spec fills the template placeholder with the drafting status's change time.
    created = path.read_text(encoding="utf-8")
    assert "{{STATUS_CHANGED}}" not in created
    assert naming.read_status_changed(created) is not None

    # A transition stamps the caller-supplied instant into the "Status changed" row.
    spec.spec_status(path, "ready", changed_at="2026-07-12T19:24:56+00:00")
    text = path.read_text(encoding="utf-8")
    assert "| **Status changed** | 2026-07-12T19:24:56+00:00 |" in text
    assert naming.read_status_changed(text) == "2026-07-12T19:24:56+00:00"


def test_stamped_template_has_a_home_for_each_dor_condition():
    """The stamped template deliberately differs from the annotated reference, so byte-sync
    is wrong. Instead protect the property: every DoR condition group has a named home."""
    t = method_text("spec-template.md")
    for needle in (
        "Checkpoint",  # DoR 3.5
        "Generated by",  # DoR 3.4
        "Failing scenario",  # DoR 2.4 bug-fix scaffold
        "Excluded",  # DoR 7.1–7.2
        "Deferred",  # DoR 7.4
        "Interface Surface",  # DoR 8
        "Instantiation",  # DoR 6.1
        "Data integrity",  # harm class (DoR 5)
        "Security",
        "Performance",
    ):
        assert needle in t, f"stamped template missing DoR home: {needle!r}"


def test_stamped_template_markers_are_unique():
    """A fresh template must have exactly 12 markers, each a unique ID — closing one marker
    should never require editing two places (the old duplicate G-001 did)."""
    markers = naming.find_markers(method_text("spec-template.md"))
    ids = [i for i, _ in markers]
    assert len(ids) == 12
    assert len(set(ids)) == len(ids), "duplicate marker IDs in the stamped template"
    # C-002: the added twelfth marker is the interface-surface determination (§8).
    assert any("interface-surface" in desc.lower() for _, desc in markers), (
        "the stamped template must force the interface-surface determination as a marker"
    )


def test_stamped_template_has_interface_surface_home():
    """C-001: the stamped template carries an Interface Surface subsection for the determination,
    documenting the three outcomes and that silence is not a valid one."""
    t = method_text("spec-template.md")
    assert "## Interface Surface" in t
    for label in ("non-trivial", "trivial, because", "not applicable, because"):
        assert label in t, f"Interface Surface home missing outcome label: {label!r}"
    assert "silence is not valid" in t, "the determination must state silence is not valid"


def test_stamped_template_has_wireframe_home():
    """C-006: the stamped template names a home for the per-spec wireframe reference — a
    non-trivial surface's wireframe is stored beside the spec."""
    t = method_text("spec-template.md")
    assert "Wireframe" in t
    assert "stored beside the spec" in t
